### ISSUE TITLE
Class not found in source with @type_check_only

### ISSUE THREAD

**Issue by ilai-deutel** [ambv/retype#22]
Hello,

I think that classes decorated with [`@type_check_only`](https://docs.python.org/3/library/typing.html#typing.type_check_only) should be allowed even if they are not present in the source file (since they are not available at runtime). Using them currently results in a `Class not found in source` error:

`foo.pyi`:

```python
from typing import type_check_only
from typing_extensions import Protocol

@type_check_only
class A(Protocol):
    def __call__(self, u: str) -> int: ...

def f(a: A) -> int: ...
```

`foo.py`:

```python
def f(a):
    return a(u='abc')
```

`retype` outputs `error: /path/to/foo.py: Class 'A' not found in source.`

I was expecting an output similar to this:
```python

from typing import TYPE_CHECKING
from typing_extensions import Protocol

if TYPE_CHECKING:
    class A(Protocol):
        def __call__(self, u: str) -> int: ...

def f(a: 'A') -> int:
    return a(u='abc')
```

**Comment by gaborbernat** [comment]
I think this makes sense, @ambv can confirm for sure. Can you create a PR with the proposed solution?

**Comment by ilai-deutel** [comment]
I am working on a PR!

**Comment by gaborbernat** [comment]
This project is being retired and archived, so we'll no longer address this.
