### ISSUE TITLE
Information: is there any public Python API?

### ISSUE THREAD

**Issue by abravalheri** [ambv/retype#35]
Hello, thank you very much for the project, it is a very useful tool!

I was wondering if there is any public Python API that allows using `retype` from a Python script itself (instead of relying on shell scripting).

For example, can I consider the functions `retype_file` and `retype_path` part of the public Python API?

This would allow scripting by installing `retype` and importing `retype_file` or `retype_path` directly instead of having to use a Popen/subprocess-based solution...

**Comment by gaborbernat** [comment]
In theory, it's public. Note, the project currently is in maintenance mode (meaning we're looking for people who have time to fix issues, add support for newer python versions).
