### ISSUE TITLE
quote forward references

### ISSUE THREAD

**Issue by carljm** [ambv/retype#6]
Unquoted forward references are valid in stub files, but not at runtime; when applying stubs to a module, retype should quote them when necessary to avoid creating a module that fails to run.

In light of PEP 563, this won't be necessary in Python 3.7, which probably reduces the motivation to implement it. But in any case, this issue should exist to document the issue and whatever resolution is decided on.

**Comment by wwuck** [comment]
@carljm Any updates on this?  Is it possible to detect the python version and optionally add the PEP563 import, or does that import have to be added in manually?

**Comment by carljm** [comment]
It has to be added manually. It would be up to @ambv how he wants to address this issue in retype, if at all.

**Comment by gaborbernat** [comment]
This project is being retired and archived, so we'll no longer address this.
