### ISSUE TITLE
Incompatible existing annotations when referencing classes in other modules

### ISSUE THREAD

**Issue by ikelos** [ambv/retype#8]
Hiya,

I came across your tool when trying out monkeytype and found it's very useful but bombs out on most of my files with errors like:

`Annotation problem in function 'blah': 36:1: incompatible existing annotation for`...

The incompatible annotations appear to be the difference between `B` and `a.B`.  I tend to import modules and then reference classes within the modules rather than importing the classes directly (in order to avoid namespace pollution).  Should retype support this situation but doesn't yet, or is there something else going on?  Happy to debug further, just wanted to figure out if this was expected behaviour or not...  5:)

Is there a flag to unilaterally write the stub's type information into the code, ignoring the existing annotations?

**Comment by gaborbernat** [comment]
This project is being retired and archived, so we'll no longer address this.
